name: Run Behave on merge or regularly
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Behave Tests
        run: behave
        uses: ./
        with:
          test-output-name: results.txt
        continue-on-error: true
