name: Run Behave on merge or regularly

steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
  with:
    python-version: 3.10.12
- uses: cryptic-wizard/run-behave-tests@v0.4.0
  with:
    test-path: example_project
    test-output-name: results.txt

name: Run Behave on merge or regularly
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Behave Tests
        run: behave
        continue-on-error: true
